on:
  rss:
    url: https://hnrss.org/newest?points=300
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        with:
          url: https://api2.pushdeer.com/message/push?pushkey=PDU8939TluIn851UVYFudK7InUZ2DULxD7FwgdIF&text=要发送的内容
          method: POST
